"""Revertir cambios

Revision ID: 201f4e3c6692
Revises: b1b506d118ea
Create Date: 2026-02-25 20:21:19.610462

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '201f4e3c6692'
down_revision = 'b1b506d118ea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('alumnos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('apaterno', sa.String(length=50), nullable=True))
        batch_op.drop_column('telefono')
        batch_op.drop_column('apellidos')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('alumnos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('apellidos', mysql.VARCHAR(length=200), nullable=True))
        batch_op.add_column(sa.Column('telefono', mysql.VARCHAR(length=20), nullable=True))
        batch_op.drop_column('apaterno')

    # ### end Alembic commands ###
